source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'puma'
gem 'activeresource', require: 'active_resource'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'rspec-rails', '~> 3.4.0'
  gem "rspec", '~> 3.4.0'
  gem "rspec-expectations", '~> 3.4.0'
  gem 'vcr'
  gem 'vcr_cable'
  gem "factory_girl_rails", "~> 4.0"
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'byebug'
  # gem "selenium-webdriver", '~> 2.35.1'
  # gem "selenium-client"
end

group :test do
  gem 'webmock', '~> 1.18.0', require: false
  gem 'capybara', '~> 2.3.0', require: false
  gem 'poltergeist', '~> 1.5.1', require: false
  gem 'simplecov', '~> 0.7.1', require: false
  gem 'ffaker', '~> 1.24.0'
  gem 'rspec-collection_matchers'
  gem 'show_me_the_cookies'
end


group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

